"""updated

Revision ID: 15cebc6e8d9b
Revises: 8cd89d3ae90e
Create Date: 2023-03-18 12:49:06.524590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15cebc6e8d9b'
down_revision = '8cd89d3ae90e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('gpa',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('gpa',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
